before_install:
  - sdk install java 25-open
  - sdk use java 25-open
install:
  - ./gradlew :gp3d-core:jar :jar --configure-on-demand -x test -x check -x checkAddonCompatibility -x checkLegacyCompatibility
