version=18.2.19
minecraftVersion=1.21.11
paperMinecraftVersion=1.21.4
legacyBukkitVersion=1.8.8
targetJavaVersion=8
legacyTargetJavaVersion=8
fabricMinecraftVersion=1.21.11
fabricLoaderVersion=0.19.3
fabricApiVersion=0.141.6+1.21.11
fabricTargetJavaVersion=21

org.gradle.jvmargs=-Dfile.encoding=UTF-8
