// Shared build logic for the per-Minecraft-version Fabric adapter modules.
//
// Every module compiles the same adapter sources in platforms/fabric-common against its own
// Minecraft target, plus any version-specific sources under its own src/. A module sets these
// extra properties before applying this script:
//   fabricAdapterTag       short name, such as mc26_1; also the relocated package in the universal jar
//   fabricMinecraftRange   Fabric version predicate of the releases the compiled adapter is verified on
//   fabricJavaVersion      minimum Java version of that Minecraft range
import org.gradle.api.tasks.SourceSetContainer
import org.gradle.language.jvm.tasks.ProcessResources

// The Fabric API modules the adapter calls, compiled against one by one so no other module can creep
// in, and declared the same way in fabric.mod.json.
extra["fabricApiModules"] = listOf(
    "fabric-api-base",
    "fabric-command-api-v2",
    "fabric-events-interaction-v0",
    "fabric-lifecycle-events-v1",
    "fabric-networking-api-v1"
)

val adapterTag = extra["fabricAdapterTag"] as String
val minecraftRange = extra["fabricMinecraftRange"] as String
val javaVersion = extra["fabricJavaVersion"] as Int
val commonDir = rootProject.file("platforms/fabric-common")

group = rootProject.group
version = rootProject.version

repositories {
    mavenCentral()
    maven("https://maven.fabricmc.net/")
}

val generateAdapterIndex = tasks.register("generateFabricAdapterIndex") {
    val output = layout.buildDirectory.dir("generated/fabric-adapter-index")
    inputs.property("tag", adapterTag)
    inputs.property("minecraftRange", minecraftRange)
    outputs.dir(output)

    doLast {
        val index = output.get().file("META-INF/griefprevention3d/fabric-adapters.properties").asFile
        index.parentFile.mkdirs()
        index.writeText(
            """
            |# Generated by the build: the adapter in this module jar and the releases it serves.
            |adapters=$adapterTag
            |adapter.$adapterTag.minecraft=$minecraftRange
            |adapter.$adapterTag.entrypoint=com.griefprevention.fabric.GriefPreventionFabric
            |adapter.$adapterTag.mixins=com.griefprevention.fabric.mixin
            |""".trimMargin()
        )
    }
}

the<SourceSetContainer>().apply {
    named("main") {
        java.srcDir(commonDir.resolve("src/main/java"))
        resources.srcDir(commonDir.resolve("src/main/resources"))
        resources.srcDir(generateAdapterIndex)
    }
    named("test") {
        java.srcDir(commonDir.resolve("src/test/java"))
    }
}

tasks.named<ProcessResources>("processResources") {
    inputs.property("version", project.version.toString())
    inputs.property("minecraftRange", minecraftRange)
    inputs.property("javaVersion", javaVersion)
    filesMatching("fabric.mod.json") {
        expand(
            "version" to project.version.toString(),
            "minecraftRange" to minecraftRange,
            "javaVersion" to javaVersion
        )
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

// FabricPermissionDefaults copies plugin.yml's permission tree; its test reads plugin.yml to check.
val bukkitDescriptor = rootProject.file("src/main/resources/plugin.yml")

dependencies {
    "testImplementation"("org.yaml:snakeyaml:2.6")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    inputs.file(bukkitDescriptor)
    systemProperty("griefprevention3d.bukkitDescriptor", bukkitDescriptor.absolutePath)
}
